"""Build the optional ApexCharts dashboard examples in examples/dashboards/.

This file is the only source. Edit here, then run `python tools/dashboards/build.py`;
`--check` fails when the committed examples differ from the generator output.

The committed examples use placeholder entity IDs and English labels. For a real
installation, print a section with your own entities and language:

    python tools/dashboards/build.py --print plan --lang pl \
        --entity plan=sensor.my_plan --entity valid=binary_sensor.my_forecast_valid ...

The plan and consumer charts need ApexCharts Card (custom:apexcharts-card) 2.2.3
or later; the controller section uses native cards only.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "examples/dashboards"
STATE_BANDS = Path(__file__).with_name("state_bands.js").read_text()
HEADER = "# Generated by tools/dashboards/build.py - do not edit; edit the generator and rebuild.\n"

# Placeholders follow examples/dashboard.yaml: replace_with_<role>.
ENTITIES = {
    "plan": "sensor.replace_with_plan",
    "valid": "binary_sensor.replace_with_forecast_valid",
    "consumer": "sensor.replace_with_consumer_compass",
    "soc": "sensor.replace_with_battery_soc",
    "load": "sensor.replace_with_load_power",
    "grid": "sensor.replace_with_grid_power",
    "pv": "sensor.replace_with_pv_power",
    "alert": "binary_sensor.replace_with_alert",
    "optimizer": "sensor.replace_with_optimizer_status",
    "machine": "sensor.replace_with_energy_compass",
    "consumer_cost": "sensor.replace_with_consumption_cost",
    "next_change": "sensor.replace_with_next_change",
    "battery_power": "sensor.replace_with_battery_power",
    "battery_state": "sensor.replace_with_battery_state",
    "charge_limit": "number.replace_with_battery_max_charging_current",
    "discharge_limit": "number.replace_with_battery_max_discharging_current",
    "grid_limit": "number.replace_with_battery_grid_charging_current",
}
CAPACITY_KWH = (
    25  # Must match the Energy Compass battery capacity, not the BMS capacity.
)

LABELS = {
    "en": {
        "locale": "en-GB",
        "plan_title": "Load / Grid / PV / SoC - history and plan",
        "now": "Now",
        "power_axis": "Power [kW]",
        "plan_suffix": "plan",
        "plan_note": """**Solid lines:** measurements up to now · **Dashed:** Energy Compass plan from now.
12 h history (power and SoC: 30 min means) + 24 h ahead. **Grid:** + import / − export. Plan SoC: capacity {capacity} kWh.

**Background (14% opacity):** CHARGE_PV yellow · CHARGE_GRID red · DISCHARGE_GRID purple · SELF_CONSUME green.
HOLD and other states gray. Narrow intervals: hover for the label.
""",
        "refreshing": "**Recalculating - showing the previous plan. The new one replaces it automatically.**",
        "available_until": "Plan available until",
        "partial": " The rest stays empty - forecasts do not cover it completely.",
        "stale": "**Forecast stale or unavailable - only measured history is shown.**",
        "consumer_title": "Consumer Compass - history and forecast",
        "history": "history",
        "forecast": "forecast",
        "consumer_note": "4 h history + 20 h ahead.\nSolid colors: history · Lighter: forecast · Empty: no data.",
        "consumer_refreshing": "Recalculating - showing the last available forecast.",
        "consumer_stale": "Forecast unavailable - history is shown.",
    },
    "pl": {
        "locale": "pl-PL",
        "plan_title": "Load / Grid / PV / SoC — historia i projekcja",
        "now": "Teraz",
        "power_axis": "Moc [kW]",
        "plan_suffix": "plan",
        "plan_note": """**Linie ciągłe:** pomiary do teraz · **Przerywane:** plan Energy Compass od teraz.
12 h historii (moc i SoC: średnie 30 min) + 24 h naprzód. **Grid:** + import / − eksport. SoC planu: pojemność {capacity} kWh.

**Tło (14% krycia):** CHARGE_PV — żółty · CHARGE_GRID — czerwony · DISCHARGE_GRID — fioletowy · SELF_CONSUME — zielony.
HOLD i pozostałe stany — szary. Krótkie przedziały: opis po najechaniu.
""",
        "refreshing": "**Przeliczanie — wyświetlany poprzedni plan. Nowy zastąpi go automatycznie.**",
        "available_until": "Plan dostępny do",
        "partial": " Dalsza część pozostaje pusta — brak pełnego pokrycia prognoz.",
        "stale": "**Prognoza nieaktualna lub niedostępna — widoczna tylko historia pomiarów.**",
        "consumer_title": "Consumer Compass — historia i prognoza",
        "history": "historia",
        "forecast": "prognoza",
        "consumer_note": "4 h historii + 20 h naprzód.\nPełne kolory: historia · Jaśniejsze: prognoza · Puste miejsce: brak danych.",
        "consumer_refreshing": "Przeliczanie — widoczna ostatnia dostępna prognoza.",
        "consumer_stale": "Prognoza niedostępna — widoczna historia.",
    },
}
LEVEL_COLORS = {
    "BOOST": "#2e7d32",
    "CHEAP": "#66bb6a",
    "NORMAL": "#78909c",
    "LIMIT": "#c62828",
}


def plan_guard(valid):
    return f"""const now = Date.now();
const valid = hass.states['{valid}'];
// The integration retains the last complete generation while its replacement runs.
const refreshing = entity.attributes.refreshing === true;
if (['unknown', 'unavailable'].includes(entity.state) ||
    (!refreshing && (valid?.state !== 'on' ||
      !(Date.parse(entity.attributes.valid_until) > now)))) return [];
const rows = (entity.attributes.intervals || []).filter(r =>
  Number.isFinite(Date.parse(r.start)) && Number.isFinite(Date.parse(r.end)) &&
  Date.parse(r.end) > Date.parse(r.start) && Date.parse(r.end) > now
).sort((a, b) => Date.parse(a.start) - Date.parse(b.start));
const points = [];
"""


def power_generator(valid, field):
    expression = (
        "r.grid_import_kwh - r.grid_export_kwh" if field == "grid" else f"r.{field}_kwh"
    )
    required = (
        "Number.isFinite(r.grid_import_kwh) && Number.isFinite(r.grid_export_kwh)"
        if field == "grid"
        else f"Number.isFinite(r.{field}_kwh)"
    )
    return (
        plan_guard(valid)
        + f"""let previousEnd = null;
let previousValue = null;
for (const r of rows) {{
  const from = Date.parse(r.start), to = Date.parse(r.end);
  const value = ({required}) ? ({expression}) / ((to - from) / 3600000) : null;
  // Clip the first slot at now, but divide by its original duration.
  const left = Math.max(from, now);
  if (previousEnd !== null && from > previousEnd) {{
    points.push([previousEnd, previousValue], [previousEnd + 1, null]);
  }}
  points.push([left, value]);
  previousEnd = to;
  previousValue = value;
}}
if (previousEnd !== null) points.push([previousEnd, previousValue]);
return points;
"""
    )


def soc_generator(valid, soc, capacity):
    return (
        plan_guard(valid)
        + f"""const capacityKwh = {capacity};
const raw = hass.states['{soc}']?.state;
const current = raw == null || raw === '' ? NaN : Number(raw);
let previousEnd = null;
for (const r of rows) {{
  const from = Date.parse(r.start), to = Date.parse(r.end);
  if (previousEnd === null && from <= now && Number.isFinite(current)) {{
    points.push([now, current]);
  }} else if (previousEnd !== null && from > previousEnd) {{
    points.push([previousEnd + 1, null]);
  }}
  const value = Number.isFinite(r.end_soc_kwh) ? r.end_soc_kwh / capacityKwh * 100 : null;
  points.push([to, value]);
  previousEnd = to;
}}
return points;
"""
    )


def plan_section(entities=ENTITIES, lang="en", capacity=CAPACITY_KWH):
    """History and projection of load, grid, PV and SoC with plan-state bands."""
    e, t = entities, LABELS[lang]
    bands = "EVAL:" + STATE_BANDS.replace("__PLAN__", e["plan"]).replace(
        "__VALID__", e["valid"]
    ).replace("__LOCALE__", t["locale"])
    series_spec = [
        ("Load", e["load"], "#42a5f5", "load"),
        ("Grid", e["grid"], "#ef5350", "grid"),
        ("PV", e["pv"], "#ffb300", "pv"),
        ("SoC", e["soc"], "#66bb6a", "soc"),
    ]
    chart = {
        "type": "custom:apexcharts-card",
        "section_mode": True,
        "grid_options": {"columns": "full", "rows": 9},
        "header": {
            "show": True,
            "title": t["plan_title"],
            "show_states": True,
            "colorize_states": True,
        },
        "graph_span": "36h",
        "span": {"offset": "+24h"},
        "update_interval": "1min",
        "hours_12": False,
        "now": {"show": True, "label": t["now"], "color": "#9e9e9e"},
        "show": {"last_updated": True},
        "yaxis": [
            {
                "id": "power",
                "decimals": 1,
                "min": "~0",
                "max": "~0",
                "apex_config": {"tickAmount": 6, "title": {"text": t["power_axis"]}},
            },
            {
                "id": "soc",
                "opposite": True,
                "min": 0,
                "max": 100,
                "decimals": 0,
                "apex_config": {"tickAmount": 5, "title": {"text": "SoC [%]"}},
            },
        ],
        "apex_config": {
            "chart": {
                "animations": {"enabled": False},
                "toolbar": {"show": False},
                "events": {"mounted": bands, "updated": bands},
            },
            "annotations": {
                "position": "back",
                "yaxis": [
                    {
                        "y": 0,
                        "yAxisIndex": 0,
                        "borderColor": "#bdbdbd",
                        "borderWidth": 2,
                        "strokeDashArray": 0,
                        "label": {
                            "text": "0 kW",
                            "position": "left",
                            "borderColor": "#757575",
                            "style": {
                                "background": "#424242",
                                "color": "#ffffff",
                                "fontSize": "10px",
                            },
                        },
                    }
                ],
            },
            "legend": {"show": True, "fontSize": "12px"},
            "grid": {"borderColor": "#424242", "strokeDashArray": 2},
            "xaxis": {"labels": {"datetimeUTC": False, "format": "dd.MM HH:mm"}},
            "tooltip": {"shared": False, "x": {"format": "dd.MM HH:mm"}},
        },
        "series": [],
    }
    for name, entity, color, field in series_spec:
        soc = field == "soc"
        chart["series"].append(
            {
                "entity": entity,
                "name": name,
                "color": color,
                "type": "line",
                "yaxis_id": "soc" if soc else "power",
                "unit": "%" if soc else "kW",
                "float_precision": 0 if soc else 2,
                "stroke_width": 2,
                "curve": "monotoneCubic",
                "extend_to": "now",
                "fill_raw": "null",
                "transform": "if (x === null || x === '') return null; const v = Number(x); "
                f"return Number.isFinite(v) ? v / {1 if soc else 1000} : null;",
                "group_by": {"func": "avg", "duration": "30min", "fill": "last"},
                "show": {"legend_value": False},
            }
        )
    for name, _, color, field in series_spec:
        soc = field == "soc"
        chart["series"].append(
            {
                "entity": e["plan"],
                "name": f"{name} · {t['plan_suffix']}",
                "color": color,
                "type": "line",
                "yaxis_id": "soc" if soc else "power",
                "unit": "%" if soc else "kW",
                "float_precision": 0 if soc else 2,
                "stroke_width": 2,
                "stroke_dash": 6,
                "curve": "stepline" if field == "grid" else "monotoneCubic",
                "extend_to": False,
                "show": {"in_header": False, "legend_value": False},
                "data_generator": soc_generator(e["valid"], e["soc"], capacity)
                if soc
                else power_generator(e["valid"], field),
            }
        )
    note = {
        "type": "markdown",
        "grid_options": {"columns": "full", "rows": "auto"},
        "content": t["plan_note"].format(capacity=capacity)
        + f"""
{{% set valid = '{e["valid"]}' %}}
{{% set plan = '{e["plan"]}' %}}
{{% set until = state_attr(plan, 'valid_until') %}}
{{% if has_value(plan) and state_attr(plan, 'refreshing') == true %}}
{t["refreshing"]}
{{% elif is_state(valid, 'on') and until and as_timestamp(until, 0) > as_timestamp(now()) %}}
{{% set coverage = state_attr(valid, 'coverage_end') %}}
{{% if coverage %}}{t["available_until"]} **{{{{ as_local(as_datetime(coverage)).strftime('%d.%m %H:%M') }}}}**.{{% endif %}}
{{% if not state_attr(valid, 'coverage_complete') %}}{t["partial"]}{{% endif %}}
{{% else %}}
{t["stale"]}
{{% endif %}}
""",
    }
    return {
        "type": "grid",
        "column_span": 4,
        "cards": [
            {
                "type": "heading",
                "heading": "Energy Compass",
                "heading_style": "title",
                "icon": "mdi:chart-timeline-variant",
            },
            chart,
            note,
        ],
    }


def level_forecast(valid, level):
    return f"""const now = Date.now();
const a = entity.attributes;
const valid = hass.states['{valid}'];
if (['unknown', 'unavailable'].includes(entity.state) ||
    (!a.refreshing && (valid?.state !== 'on' || !(Date.parse(a.valid_until) > now)))) return [];
const left = Math.max(now, start.getTime());
const coverage = Date.parse(valid?.attributes?.coverage_end);
const right = Math.min(end.getTime(), Number.isFinite(coverage) ? coverage : end.getTime());
if (right <= left) return [];
const points = new Map([[left, 0], [right, 0]]);
for (const row of (a.outlook || [])) {{
  const from = Math.max(left, Date.parse(row.start));
  const to = Math.min(right, Date.parse(row.end));
  if (!(to > from) || !['BOOST', 'CHEAP', 'NORMAL', 'LIMIT'].includes(row.level)) continue;
  const value = row.level === '{level}' ? 1 : 0;
  points.set(from, value);
  points.set(to - 1, value);
  points.set(to, 0);
}}
return [...points].sort((a, b) => a[0] - b[0]);
"""


def consumer_section(entities=ENTITIES, lang="en"):
    """Consumer Compass levels: 4 h of history and a 20 h forecast."""
    e, t = entities, LABELS[lang]
    chart = {
        "type": "custom:apexcharts-card",
        "section_mode": True,
        "grid_options": {"columns": "full", "rows": 4},
        "header": {"show": True, "title": t["consumer_title"], "show_states": False},
        "graph_span": "24h",
        "span": {"offset": "+20h"},
        "update_interval": "1min",
        "hours_12": False,
        "now": {"show": True, "label": t["now"], "color": "#ffb300"},
        "yaxis": [{"min": 0, "max": 1, "show": False}],
        "apex_config": {
            "chart": {
                "animations": {"enabled": False},
                "toolbar": {"show": False},
                "zoom": {"enabled": False},
            },
            "grid": {
                "show": False,
                "padding": {"top": 10, "bottom": 0, "left": 8, "right": 8},
            },
            "markers": {"size": 0},
            "dataLabels": {"enabled": False},
            "xaxis": {
                "labels": {
                    "datetimeUTC": False,
                    "format": "HH:mm",
                    "hideOverlappingLabels": True,
                },
                "tooltip": {"enabled": False},
                "axisBorder": {"show": False},
                "axisTicks": {"show": False},
            },
            "legend": {
                "show": True,
                "position": "bottom",
                "fontSize": "12px",
                "customLegendItems": list(LEVEL_COLORS),
                "markers": {"fillColors": list(LEVEL_COLORS.values())},
                "onItemClick": {"toggleDataSeries": False},
                "onItemHover": {"highlightDataSeries": False},
            },
            "tooltip": {
                "shared": False,
                "intersect": False,
                "custom": f"""EVAL:function({{seriesIndex, dataPointIndex, w}}) {{
  const value = w.globals.series[seriesIndex]?.[dataPointIndex];
  if (value !== 1) return '';
  const timestamp = w.globals.seriesX[seriesIndex]?.[dataPointIndex];
  if (!Number.isFinite(timestamp)) return '';
  const name = w.globals.seriesNames[seriesIndex];
  const date = new Date(timestamp).toLocaleString('{t["locale"]}', {{day:'2-digit', month:'2-digit', hour:'2-digit', minute:'2-digit'}});
  return '<div style="padding:8px 12px"><b>' + name + '</b><br>' + date + '</div>';
}}""",
            },
        },
        "series": [],
    }
    for projected in (False, True):
        for level, color in LEVEL_COLORS.items():
            series = {
                "entity": e["plan"] if projected else e["consumer"],
                "name": f"{level} · {t['forecast'] if projected else t['history']}",
                "color": color,
                "type": "area",
                "curve": "stepline",
                "stroke_width": 0,
                "opacity": 0.55 if projected else 1,
                "extend_to": False if projected else "now",
                "show": {"in_header": False, "legend_value": False},
            }
            if projected:
                series["data_generator"] = level_forecast(e["valid"], level)
            else:
                series["transform"] = f"return x === '{level}' ? 1 : 0;"
                series["fill_raw"] = "zero"
            chart["series"].append(series)
    note = {
        "type": "markdown",
        "grid_options": {"columns": "full", "rows": "auto"},
        "content": f"""**{t["now"]}: {{{{ states('{e["consumer"]}') }}}}** · {t["consumer_note"]}
{{% if state_attr('{e["plan"]}', 'refreshing') == true %}}
{t["consumer_refreshing"]}
{{% elif not is_state('{e["valid"]}', 'on') %}}
{t["consumer_stale"]}
{{% endif %}}""",
    }
    return {"type": "grid", "column_span": 4, "cards": [chart, note]}


# --- Controller panel and diagnostics -------------------------------------
# The Deye controller package fixes these entity IDs.
MODE = "input_select.energy_compass_deye_mode"
RUNTIME = "sensor.energy_compass_deye_runtime"
SESSION = "input_boolean.energy_compass_deye_session"
RESTORE = "input_boolean.energy_compass_deye_restore_pending"
NEXT_TOU = "sensor.energy_compass_deye_next_tou"
PANEL_TEXT = {
    "en": {
        "title": "Battery",
        "subtitle": "Energy Compass · plan and execution",
        "check": "Check control",
        "now": "Battery now",
        "decision": "Compass decision",
        "plan": "Battery plan",
        "next24": "Next 24 hours",
        "soc_forecast": "Charge forecast · 24 h",
        "soc_series": "SOC forecast",
        "consumption": "Household consumption compass",
        "history": "History",
        "soc_24h": "Charge · last 24 h",
        "power_24h": "Power · + discharge / − charge",
        "control_24h": "Control history · 24 h",
        "h_mode": "Control",
        "h_machine": "Battery recommendation",
        "h_runtime": "Controller state",
        "h_battery": "Battery operation",
        "charge": "Charge",
        "power": "Battery power",
        "mode": "Control mode",
        "diagnostics": "Energy Compass diagnostics",
        "limits": "Inverter limits · read-back",
        "l_charge": "Charge limit",
        "l_discharge": "Discharge limit",
        "l_grid": "Grid charge limit",
        "l_tou": "Next TOU change",
        "states": "{'CHARGE_PV':'Charging from PV','CHARGE_GRID':'Charging from grid','DISCHARGE_GRID':'Selling to grid','SELF_CONSUME':'Powering the house','HOLD':'Holding','CURTAIL':'Holding (PV curtailment)','BASE':'Base mode'}",
        "modes": "{'Auto':'Automatic','Simulation':'Simulation','Off':'Off'}",
        "levels": "{'BOOST':'🟢 Use more','CHEAP':'🟢 Cheap use','NORMAL':'⚪ Normal use','LIMIT':'🔴 Limit use'}",
        "levels_lc": "{'BOOST':'use more','CHEAP':'cheap use','NORMAL':'normal use','LIMIT':'limit use'}",
        "discharging": "Discharging",
        "charging": "Charging",
        "idle": "Idle",
        "no_power": "No current power reading.",
        "control": "Control",
        "unavailable": "Unavailable",
        "confirmed": "Settings confirmed",
        "no_confirmation": "No mode confirmation",
        "status": "Controller status",
        "no_data": "No data",
        "no_advice": "No recommendation",
        "segment_until": "Current segment until",
        "no_current": "**No current recommendation.** The plan expired or the forecast is unavailable.",
        "soc_target": "SOC target",
        "soc_floor": "SOC floor",
        "of_controller": "of the controller",
        "then": "Then",
        "measure_note": "Power shows what the battery actually does. The recommendation and confirmation refer to the plan and the settings.",
        "stale_forecast": "The forecast is not current. The schedule is not a current recommendation.",
        "compass_problem": "The Compass reports a problem.",
        "controller": "Controller",
        "no_fresh": "No fresh confirmation of the inverter settings.",
        "unconfirmed_writes": "Unconfirmed writes",
        "from": "From",
        "battery_plan": "Battery plan",
        "soc_end": "SOC at the end",
        "now_row": "Now",
        "plan_note": "The plan can change after new measurements. SOC is computed for the configured",
        "no_schedule": "Schedule unavailable - waiting for a current forecast.",
        "extra_cost": "PLN/kWh of extra use",
        "next_change": "Next change",
        "cost_note": "Estimated cost of extra energy used in the house, with the battery taken into account. This is not the grid purchase price.",
        "no_hint": "No consumption hint - no current forecast.",
        "param": "Parameter",
        "state": "State",
        "optimizer": "Optimizer",
        "reason": "Reason",
        "confirmed_mode": "Confirmed mode",
        "last_confirmation": "Last confirmation",
        "plan_created": "Plan created",
        "controller_valid": "Controller plan valid until",
        "forecast_until": "Forecast until",
        "active_tou": "Active TOU program",
        "uncertain": "Unconfirmed writes",
        "session": "Controller session",
        "restore": "Restore after the session",
        "none": "None",
        "model_notes": "Model notes",
        "restore_note": "The restore flag can be on during an Auto session. On its own it does not mean a fault.",
        "currency": "PLN",
    },
    "pl": {
        "title": "Bateria",
        "subtitle": "Energy Compass · plan i wykonanie",
        "check": "Sprawdź sterowanie",
        "now": "Bateria teraz",
        "decision": "Decyzja Kompasu",
        "plan": "Plan baterii",
        "next24": "Najbliższe 24 godziny",
        "soc_forecast": "Prognoza naładowania · 24 h",
        "soc_series": "Prognoza SOC",
        "consumption": "Kompas zużycia w domu",
        "history": "Historia",
        "soc_24h": "Naładowanie · ostatnie 24 h",
        "power_24h": "Moc · + rozładowanie / − ładowanie",
        "control_24h": "Historia sterowania · 24 h",
        "h_mode": "Sterowanie",
        "h_machine": "Zalecenie baterii",
        "h_runtime": "Stan sterownika",
        "h_battery": "Praca baterii",
        "charge": "Naładowanie",
        "power": "Moc baterii",
        "mode": "Tryb sterowania",
        "diagnostics": "Diagnostyka Energy Compass",
        "limits": "Limity falownika · odczyt",
        "l_charge": "Limit ładowania",
        "l_discharge": "Limit rozładowania",
        "l_grid": "Limit ładowania z sieci",
        "l_tou": "Następna zmiana TOU",
        "states": "{'CHARGE_PV':'Ładowanie z PV','CHARGE_GRID':'Ładowanie z sieci','DISCHARGE_GRID':'Sprzedaż do sieci','SELF_CONSUME':'Zasilanie domu','HOLD':'Podtrzymanie','CURTAIL':'Podtrzymanie (ograniczenie PV)','BASE':'Tryb bazowy'}",
        "modes": "{'Auto':'Automatyczne','Simulation':'Symulacja','Off':'Wyłączone'}",
        "levels": "{'BOOST':'🟢 Zwiększ zużycie','CHEAP':'🟢 Tanie zużycie','NORMAL':'⚪ Zwykłe zużycie','LIMIT':'🔴 Ogranicz zużycie'}",
        "levels_lc": "{'BOOST':'zwiększ zużycie','CHEAP':'tanie zużycie','NORMAL':'zwykłe zużycie','LIMIT':'ogranicz zużycie'}",
        "discharging": "Rozładowanie",
        "charging": "Ładowanie",
        "idle": "Spoczynek",
        "no_power": "Brak aktualnego pomiaru mocy.",
        "control": "Sterowanie",
        "unavailable": "Niedostępne",
        "confirmed": "Ustawienia potwierdzone",
        "no_confirmation": "Brak potwierdzenia trybu",
        "status": "Status sterownika",
        "no_data": "Brak danych",
        "no_advice": "Brak zalecenia",
        "segment_until": "Bieżący odcinek do",
        "no_current": "**Brak aktualnego zalecenia.** Plan wygasł lub prognoza jest niedostępna.",
        "soc_target": "Cel SOC",
        "soc_floor": "Próg SOC",
        "of_controller": "sterownika",
        "then": "Następnie",
        "measure_note": "Pomiar mocy pokazuje rzeczywistą pracę baterii. Zalecenie i potwierdzenie dotyczą planu oraz ustawień.",
        "stale_forecast": "Prognoza nie jest aktualna. Harmonogram nie stanowi bieżącego zalecenia.",
        "compass_problem": "Kompas zgłasza problem.",
        "controller": "Sterownik",
        "no_fresh": "Brak świeżego potwierdzenia ustawień falownika.",
        "unconfirmed_writes": "Niepotwierdzone zapisy",
        "from": "Od",
        "battery_plan": "Plan baterii",
        "soc_end": "SOC na koniec",
        "now_row": "Teraz",
        "plan_note": "Plan może się zmienić po nowych pomiarach. SOC wyliczony dla skonfigurowanych",
        "no_schedule": "Harmonogram niedostępny — oczekiwanie na aktualną prognozę.",
        "extra_cost": "zł/kWh dodatkowego zużycia",
        "next_change": "Następna zmiana",
        "cost_note": "Szacowany koszt dodatkowej energii zużytej w domu, z uwzględnieniem baterii. To nie cena zakupu z sieci.",
        "no_hint": "Wskazówka zużycia niedostępna — brak aktualnej prognozy.",
        "param": "Parametr",
        "state": "Stan",
        "optimizer": "Optymalizator",
        "reason": "Powód",
        "confirmed_mode": "Tryb potwierdzony",
        "last_confirmation": "Ostatnie potwierdzenie",
        "plan_created": "Plan utworzony",
        "controller_valid": "Plan sterownika ważny do",
        "forecast_until": "Prognoza do",
        "active_tou": "Aktywny program TOU",
        "uncertain": "Niepotwierdzone zapisy",
        "session": "Sesja sterownika",
        "restore": "Przywrócenie po zakończeniu sesji",
        "none": "Brak",
        "model_notes": "Uwagi modelu",
        "restore_note": "Flaga przywrócenia może być aktywna podczas sesji Auto. Sama nie oznacza awarii.",
        "currency": "zł",
    },
}
COLORS = "{'CHARGE_PV':'🟢','CHARGE_GRID':'🔵','DISCHARGE_GRID':'🟠','SELF_CONSUME':'🟣','HOLD':'⚪','CURTAIL':'⚪','BASE':'⚪'}"


def _fill(text, e, t, capacity=None):
    """Replace @role@ with entity IDs and @t:key@ with labels."""
    out = re.sub(r"@t:([a-z_0-9]+)@", lambda m: t[m.group(1)], text)
    out = re.sub(r"@([a-z_]+)@", lambda m: e[m.group(1)], out)
    return out.replace("@CAPACITY@", str(capacity))


PANEL_BASE = (
    """{% set labels = @t:states@ %}
{% set colors = """
    + COLORS
    + """ %}
{% set rt = state_attr('"""
    + RUNTIME
    + """','runtime') or {} %}
{% set plan = '@plan@' %}
{% set valid = is_state('@valid@','on') and as_timestamp(state_attr(plan,'valid_until'),0) > as_timestamp(now()) %}
{% set fresh = as_timestamp(rt.get('original_deadline'),0) > as_timestamp(now()) and as_timestamp(rt.get('last_confirmation'),0) > 0 %}
"""
)


def _md(title, body, e, t, capacity=None, columns=12):
    return {
        "type": "markdown",
        "title": _fill(title, e, t),
        "content": _fill(PANEL_BASE + body.strip(), e, t, capacity),
        "grid_options": {"columns": columns, "rows": "auto"},
    }


def _heading(text, icon, style="subtitle"):
    return {"type": "heading", "heading": text, "heading_style": style, "icon": icon}


def panel_section(entities=ENTITIES, lang="en", capacity=CAPACITY_KWH):
    """Deye controller panel: health, battery now, decision, 24 h plan, consumption, history."""
    e, t = entities, PANEL_TEXT[lang]
    alert = _md(
        "@t:check@",
        """
{% if not valid %}⚠️ @t:stale_forecast@{% endif %}
{% if is_state('@alert@','on') %}
⚠️ {{ state_attr('@alert@','reason') or '@t:compass_problem@' }}
{% endif %}
{% if is_state('"""
        + MODE
        + """','Auto') %}
{% if rt.get('code') != 'ok' %}⚠️ @t:controller@: {{ rt.get('reason') or rt.get('code') or '@t:no_data@' }}{% endif %}
{% if not fresh %}⚠️ @t:no_fresh@{% endif %}
{% if rt.get('uncertain') %}⚠️ @t:unconfirmed_writes@: {{ rt.get('uncertain')|length }}.{% endif %}
{% if rt.get('warning') %}⚠️ {{ rt.warning }}{% endif %}
{% endif %}
""",
        e,
        t,
        columns=24,
    )
    alert = {
        "type": "conditional",
        "grid_options": {"columns": 24, "rows": "auto"},
        "conditions": [
            {
                "condition": "or",
                "conditions": [
                    {"condition": "state", "entity": e["valid"], "state_not": "on"},
                    {"condition": "state", "entity": e["alert"], "state": "on"},
                    {
                        "condition": "and",
                        "conditions": [
                            {"condition": "state", "entity": MODE, "state": "Auto"},
                            {
                                "condition": "state",
                                "entity": RUNTIME,
                                "state_not": "ok",
                            },
                        ],
                    },
                ],
            }
        ],
        "card": alert,
    }
    now_card = {
        "type": "vertical-stack",
        "grid_options": {"columns": 12, "rows": "auto"},
        "cards": [
            {
                "type": "horizontal-stack",
                "cards": [
                    {
                        "type": "tile",
                        "entity": e["soc"],
                        "name": t["charge"],
                        "color": "green",
                    },
                    {
                        "type": "tile",
                        "entity": e["battery_power"],
                        "name": t["power"],
                        "color": "purple",
                    },
                ],
            },
            _md(
                "@t:now@",
                """
{% set power = states('@battery_power@') %}
{% if is_number(power) %}
**{{ '@t:discharging@' if power|float > 50 else '@t:charging@' if power|float < -50 else '@t:idle@' }} · {{ (power|float|abs / 1000)|round(2) }} kW**
{% else %}
@t:no_power@
{% endif %}

@t:control@: **{{ @t:modes@.get(states('"""
                + MODE
                + """'),'@t:unavailable@') }}**

{% if is_state('"""
                + MODE
                + """','Auto') and fresh and rt.get('code') == 'ok' and not rt.get('uncertain') %}
@t:confirmed@: **{{ labels.get(rt.get('confirmed_mode'),'@t:no_confirmation@') }}**
{% else %}
@t:status@: **{{ rt.get('reason') or rt.get('code') or '@t:no_data@' }}**
{% endif %}
""",
                e,
                t,
            ),
            {
                "type": "tile",
                "entity": MODE,
                "name": t["mode"],
                "icon": "mdi:compass",
                "features": [{"type": "select-options"}],
            },
        ],
    }
    decision = _md(
        "@t:decision@",
        """
{% set mode = states('@machine@') %}
{% if valid %}
### {{ colors.get(mode,'⚪') }} {{ labels.get(mode,'@t:no_advice@') }}
{% set ns = namespace(row=none) %}
{% for row in state_attr(plan,'intervals') or [] %}
{% if as_timestamp(row.start,0) <= as_timestamp(now()) < as_timestamp(row.end,0) %}{% set ns.row = row %}{% endif %}
{% endfor %}
{% if ns.row %}
@t:segment_until@ **{{ as_local(as_datetime(ns.row.end)).strftime('%H:%M') }}**.
{% endif %}
{% else %}
@t:no_current@
{% endif %}

{% set n = rt.get('active_tou',0)|int %}
{% set confirmed = rt.get('confirmed') or {} %}
{% set prefix = state_attr('sensor.energy_compass_deye_tou_settings','prefix') or '' %}
{% set target = confirmed.get('number.' ~ prefix ~ n ~ '_soc') %}
{% if is_state('"""
        + MODE
        + """','Auto') and fresh and rt.get('code') == 'ok' and not rt.get('uncertain') and target is not none %}
{{ '@t:soc_target@' if rt.get('confirmed_mode') == 'CHARGE_GRID' else '@t:soc_floor@' }} @t:of_controller@: **{{ target|round(0)|int }}%**
{% endif %}

{% if valid %}
{% set ns = namespace(next=none) %}
{% for row in state_attr(plan,'intervals') or [] %}
{% if not ns.next and as_timestamp(row.start,0) > as_timestamp(now()) and row.state != mode %}{% set ns.next = row %}{% endif %}
{% endfor %}
{% if ns.next %}
@t:then@: **{{ labels.get(ns.next.state,ns.next.state) }}**, {{ as_local(as_datetime(ns.next.start)).strftime('%d.%m %H:%M') }}.
{% endif %}
{% endif %}

@t:measure_note@
""",
        e,
        t,
    )
    timeline = _md(
        "@t:next24@",
        """
{% if valid %}
{% set ns = namespace(rows=[], start=none, end=none, mode=none, soc=none) %}
{% for r in state_attr(plan,'intervals') or [] %}
{% if as_timestamp(r.end,0) > as_timestamp(now()) and as_timestamp(r.start,0) < as_timestamp(now())+86400 %}
{% if ns.mode != r.state %}
{% if ns.mode is not none %}{% set ns.rows = ns.rows + [{'start':ns.start,'end':ns.end,'mode':ns.mode,'soc':ns.soc}] %}{% endif %}
{% set ns.start = r.start %}{% set ns.mode = r.state %}
{% endif %}
{% set ns.end = r.end %}{% set ns.soc = r.end_soc_kwh %}
{% endif %}
{% endfor %}
{% if ns.mode is not none %}{% set ns.rows = ns.rows + [{'start':ns.start,'end':ns.end,'mode':ns.mode,'soc':ns.soc}] %}{% endif %}
| @t:from@ | @t:battery_plan@ | @t:soc_end@ |
|:--|:--|--:|
{% for r in ns.rows %}| {{ '@t:now_row@' if as_timestamp(r.start,0) <= as_timestamp(now()) else as_local(as_datetime(r.start)).strftime('%d.%m %H:%M') }} | {{ colors.get(r.mode,'⚪') }} {{ labels.get(r.mode,r.mode) }} | {{ (r.soc|float / @CAPACITY@ * 100)|round(0)|int }}% |
{% endfor %}

@t:plan_note@ @CAPACITY@ kWh.
{% else %}
@t:no_schedule@
{% endif %}
""",
        e,
        t,
        capacity,
    )
    forecast = {
        "type": "custom:apexcharts-card",
        "grid_options": {"columns": 12, "rows": "auto"},
        "header": {"show": True, "title": t["soc_forecast"]},
        "graph_span": "24h",
        "span": {"start": "minute"},
        "update_interval": "1min",
        "now": {"show": True, "label": t["now_row"]},
        "hours_12": False,
        "yaxis": [{"min": 0, "max": 100, "decimals": 0}],
        "apex_config": {
            "chart": {"height": 260, "toolbar": {"show": False}},
            "legend": {"show": False},
            "xaxis": {"labels": {"datetimeUTC": False}},
            "tooltip": {"x": {"format": "dd.MM HH:mm"}},
        },
        "series": [
            {
                "entity": e["plan"],
                "name": t["soc_series"],
                "unit": "%",
                "type": "area",
                "color": "#43a047",
                "opacity": 0.15,
                "stroke_width": 2,
                "curve": "straight",
                "extend_to": False,
                "float_precision": 0,
                "data_generator": f"""const a = entity.attributes, now = Date.now();
if (hass.states['{e["valid"]}']?.state !== 'on' || !(Date.parse(a.valid_until) > now)) return [];
const rows = (a.intervals || []).filter(r => Date.parse(r.end) > now && Date.parse(r.end) <= now + 86400000);
const points = rows.map(r => [Date.parse(r.end), Math.max(0, Math.min(100, Number(r.end_soc_kwh) / {capacity} * 100))]);
const soc = hass.states['{e["soc"]}'];
const reported = Date.parse(soc?.attributes?.reported_at ?? soc?.last_updated);
if (soc && Number.isFinite(Number(soc.state)) && now - reported < 90000) points.unshift([now, Number(soc.state)]);
return points;""",
            }
        ],
    }
    consumption = _md(
        "@t:consumption@",
        """
{% if valid %}
{% set level = states('@consumer@') %}
{% set cost = states('@consumer_cost@') %}
**{{ @t:levels@.get(level,'@t:no_advice@') }}**
{% if is_number(cost) %} · {{ cost|float|round(3) }} @t:extra_cost@{% endif %}

{% set change = states('@next_change@') %}
{% if as_timestamp(change,0) > as_timestamp(now()) %}
@t:next_change@: **{{ @t:levels_lc@.get(state_attr('@next_change@','next_level'),'@t:no_data@') }}**, {{ as_local(as_datetime(change)).strftime('%d.%m %H:%M') }}.
{% endif %}

@t:cost_note@
{% else %}
@t:no_hint@
{% endif %}
""",
        e,
        t,
        columns=24,
    )
    history = [
        {
            "type": "sensor",
            "entity": e["soc"],
            "name": t["soc_24h"],
            "graph": "line",
            "hours_to_show": 24,
            "detail": 2,
            "grid_options": {"columns": 12, "rows": "auto"},
        },
        {
            "type": "sensor",
            "entity": e["battery_power"],
            "name": t["power_24h"],
            "graph": "line",
            "hours_to_show": 24,
            "detail": 2,
            "grid_options": {"columns": 12, "rows": "auto"},
        },
        {
            "type": "history-graph",
            "title": t["control_24h"],
            "hours_to_show": 24,
            "grid_options": {"columns": 24, "rows": "auto"},
            "entities": [
                {"entity": MODE, "name": t["h_mode"]},
                {"entity": e["machine"], "name": t["h_machine"]},
                {"entity": RUNTIME, "name": t["h_runtime"]},
                {"entity": e["battery_state"], "name": t["h_battery"]},
            ],
        },
    ]
    return {
        "type": "grid",
        "column_span": 2,
        "cards": [
            {
                "type": "heading",
                "heading": t["title"],
                "heading_style": "title",
                "icon": "mdi:home-battery",
            },
            alert,
            now_card,
            decision,
            _heading(t["plan"], "mdi:chart-timeline-variant"),
            timeline,
            forecast,
            consumption,
            _heading(t["history"], "mdi:history"),
            *history,
        ],
    }


def diagnostics_section(entities=ENTITIES, lang="en"):
    """Deye controller diagnostics: plan and controller freshness, inverter limit read-back."""
    e, t = entities, PANEL_TEXT[lang]
    date = "as_local(as_datetime({v})).strftime('%d.%m %H:%M:%S') if as_timestamp({v},0) else '@t:none@'"
    rows = [
        ("optimizer", "states('@optimizer@')"),
        ("controller", "rt.get('code','@t:no_data@')"),
        ("reason", "rt.get('reason','—')"),
        (
            "confirmed_mode",
            "labels.get(rt.get('confirmed_mode'),rt.get('confirmed_mode','—'))",
        ),
        ("last_confirmation", date.format(v="rt.get('last_confirmation')")),
        ("plan_created", date.format(v="state_attr(plan,'generated_at')")),
        ("controller_valid", date.format(v="rt.get('original_deadline')")),
        (
            "forecast_until",
            date.format(v="state_attr('@valid@','coverage_end')").replace(
                "%H:%M:%S", "%H:%M"
            ),
        ),
        ("active_tou", "rt.get('active_tou','—')"),
        ("uncertain", "rt.get('uncertain',[])|length"),
        ("session", f"states('{SESSION}')"),
        ("restore", f"states('{RESTORE}')"),
    ]
    table = "| @t:param@ | @t:state@ |\n|:--|:--|\n" + "\n".join(
        f"| @t:{k}@ | {{{{ {v} }}}} |" for k, v in rows
    )
    diagnostics = _md(
        "@t:diagnostics@",
        table
        + """

{% if rt.get('warning') %}⚠️ {{ rt.warning }}{% endif %}

{% if state_attr(plan,'reasons') %}@t:model_notes@: {{ state_attr(plan,'reasons')|join(', ') }}.{% endif %}

@t:restore_note@
""",
        e,
        t,
    )
    del diagnostics["grid_options"]
    limits = {
        "type": "entities",
        "title": t["limits"],
        "show_header_toggle": False,
        "entities": [
            {
                "type": "simple-entity",
                "entity": e["charge_limit"],
                "name": t["l_charge"],
            },
            {
                "type": "simple-entity",
                "entity": e["discharge_limit"],
                "name": t["l_discharge"],
            },
            {"type": "simple-entity", "entity": e["grid_limit"], "name": t["l_grid"]},
            {"type": "simple-entity", "entity": NEXT_TOU, "name": t["l_tou"]},
        ],
    }
    return {
        "type": "grid",
        "cards": [
            _heading(t["diagnostics"], "mdi:wrench-outline", "title"),
            diagnostics,
            limits,
        ],
    }


SECTIONS = {
    "plan": plan_section,
    "consumer": consumer_section,
    "panel": panel_section,
    "diagnostics": diagnostics_section,
}


def dump(value):
    return HEADER + yaml.safe_dump(
        value, sort_keys=False, allow_unicode=True, width=120
    )


def outputs():
    return {
        OUT / "plan_chart.yaml": dump(plan_section()),
        OUT / "consumer_compass_chart.yaml": dump(consumer_section()),
        OUT / "controller_panel.yaml": dump(panel_section()),
        OUT / "controller_diagnostics.yaml": dump(diagnostics_section()),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed examples are stale"
    )
    parser.add_argument(
        "--print",
        choices=list(SECTIONS),
        help="print one section instead of writing the examples",
    )
    parser.add_argument("--lang", choices=list(LABELS), default="en")
    parser.add_argument(
        "--entity",
        action="append",
        default=[],
        metavar="ROLE=ENTITY_ID",
        help=f"roles: {', '.join(ENTITIES)}",
    )
    parser.add_argument(
        "--capacity",
        type=float,
        default=CAPACITY_KWH,
        help="battery capacity in kWh (plan chart)",
    )
    args = parser.parse_args(argv)
    if args.print:
        entities = ENTITIES | dict(item.split("=", 1) for item in args.entity)
        unknown = set(entities) - set(ENTITIES)
        if unknown:
            parser.error(f"unknown role: {', '.join(sorted(unknown))}")
        kwargs = {"capacity": args.capacity} if args.print in ("plan", "panel") else {}
        sys.stdout.write(dump(SECTIONS[args.print](entities, args.lang, **kwargs)))
        return 0
    stale = [
        path
        for path, text in outputs().items()
        if not path.exists() or path.read_text() != text
    ]
    if args.check:
        for path in stale:
            print(
                f"stale: {path.relative_to(REPO)} - run python tools/dashboards/build.py",
                file=sys.stderr,
            )
        return 1 if stale else 0
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
