"""Build the optional ApexCharts dashboard examples in examples/dashboards/.

This file is the only source. Edit here, then run `python tools/dashboards/build.py`;
`--check` fails when the committed examples differ from the generator output.

The committed examples use placeholder entity IDs and English labels. For a real
installation, print a section with your own entities and language:

    python tools/dashboards/build.py --print plan --lang pl \
        --entity plan=sensor.my_plan --entity valid=binary_sensor.my_forecast_valid ...

The plan and consumer charts need ApexCharts Card (custom:apexcharts-card) 2.2.3
or later; the controller section uses native cards only.
"""

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "examples/dashboards"
STATE_BANDS = Path(__file__).with_name("state_bands.js").read_text()
HEADER = "# Generated by tools/dashboards/build.py - do not edit; edit the generator and rebuild.\n"

# Placeholders follow examples/dashboard.yaml: replace_with_<role>.
ENTITIES = {
    "plan": "sensor.replace_with_plan",
    "valid": "binary_sensor.replace_with_forecast_valid",
    "consumer": "sensor.replace_with_consumer_compass",
    "soc": "sensor.replace_with_battery_soc",
    "load": "sensor.replace_with_load_power",
    "grid": "sensor.replace_with_grid_power",
    "pv": "sensor.replace_with_pv_power",
}
CAPACITY_KWH = (
    25  # Must match the Energy Compass battery capacity, not the BMS capacity.
)

LABELS = {
    "en": {
        "locale": "en-GB",
        "plan_title": "Load / Grid / PV / SoC - history and plan",
        "now": "Now",
        "power_axis": "Power [kW]",
        "plan_suffix": "plan",
        "plan_note": """**Solid lines:** measurements up to now · **Dashed:** Energy Compass plan from now.
12 h history (power and SoC: 30 min means) + 24 h ahead. **Grid:** + import / − export. Plan SoC: capacity {capacity} kWh.

**Background (14% opacity):** CHARGE_PV yellow · CHARGE_GRID red · DISCHARGE_GRID purple · SELF_CONSUME green.
HOLD and other states gray. Narrow intervals: hover for the label.
""",
        "refreshing": "**Recalculating - showing the previous plan. The new one replaces it automatically.**",
        "available_until": "Plan available until",
        "partial": " The rest stays empty - forecasts do not cover it completely.",
        "stale": "**Forecast stale or unavailable - only measured history is shown.**",
        "consumer_title": "Consumer Compass - history and forecast",
        "history": "history",
        "forecast": "forecast",
        "consumer_note": "4 h history + 20 h ahead.\nSolid colors: history · Lighter: forecast · Empty: no data.",
        "consumer_refreshing": "Recalculating - showing the last available forecast.",
        "consumer_stale": "Forecast unavailable - history is shown.",
    },
    "pl": {
        "locale": "pl-PL",
        "plan_title": "Load / Grid / PV / SoC — historia i projekcja",
        "now": "Teraz",
        "power_axis": "Moc [kW]",
        "plan_suffix": "plan",
        "plan_note": """**Linie ciągłe:** pomiary do teraz · **Przerywane:** plan Energy Compass od teraz.
12 h historii (moc i SoC: średnie 30 min) + 24 h naprzód. **Grid:** + import / − eksport. SoC planu: pojemność {capacity} kWh.

**Tło (14% krycia):** CHARGE_PV — żółty · CHARGE_GRID — czerwony · DISCHARGE_GRID — fioletowy · SELF_CONSUME — zielony.
HOLD i pozostałe stany — szary. Krótkie przedziały: opis po najechaniu.
""",
        "refreshing": "**Przeliczanie — wyświetlany poprzedni plan. Nowy zastąpi go automatycznie.**",
        "available_until": "Plan dostępny do",
        "partial": " Dalsza część pozostaje pusta — brak pełnego pokrycia prognoz.",
        "stale": "**Prognoza nieaktualna lub niedostępna — widoczna tylko historia pomiarów.**",
        "consumer_title": "Consumer Compass — historia i prognoza",
        "history": "historia",
        "forecast": "prognoza",
        "consumer_note": "4 h historii + 20 h naprzód.\nPełne kolory: historia · Jaśniejsze: prognoza · Puste miejsce: brak danych.",
        "consumer_refreshing": "Przeliczanie — widoczna ostatnia dostępna prognoza.",
        "consumer_stale": "Prognoza niedostępna — widoczna historia.",
    },
}
LEVEL_COLORS = {
    "BOOST": "#2e7d32",
    "CHEAP": "#66bb6a",
    "NORMAL": "#78909c",
    "LIMIT": "#c62828",
}


def plan_guard(valid):
    return f"""const now = Date.now();
const valid = hass.states['{valid}'];
// The integration retains the last complete generation while its replacement runs.
const refreshing = entity.attributes.refreshing === true;
if (['unknown', 'unavailable'].includes(entity.state) ||
    (!refreshing && (valid?.state !== 'on' ||
      !(Date.parse(entity.attributes.valid_until) > now)))) return [];
const rows = (entity.attributes.intervals || []).filter(r =>
  Number.isFinite(Date.parse(r.start)) && Number.isFinite(Date.parse(r.end)) &&
  Date.parse(r.end) > Date.parse(r.start) && Date.parse(r.end) > now
).sort((a, b) => Date.parse(a.start) - Date.parse(b.start));
const points = [];
"""


def power_generator(valid, field):
    expression = (
        "r.grid_import_kwh - r.grid_export_kwh" if field == "grid" else f"r.{field}_kwh"
    )
    required = (
        "Number.isFinite(r.grid_import_kwh) && Number.isFinite(r.grid_export_kwh)"
        if field == "grid"
        else f"Number.isFinite(r.{field}_kwh)"
    )
    return (
        plan_guard(valid)
        + f"""let previousEnd = null;
let previousValue = null;
for (const r of rows) {{
  const from = Date.parse(r.start), to = Date.parse(r.end);
  const value = ({required}) ? ({expression}) / ((to - from) / 3600000) : null;
  // Clip the first slot at now, but divide by its original duration.
  const left = Math.max(from, now);
  if (previousEnd !== null && from > previousEnd) {{
    points.push([previousEnd, previousValue], [previousEnd + 1, null]);
  }}
  points.push([left, value]);
  previousEnd = to;
  previousValue = value;
}}
if (previousEnd !== null) points.push([previousEnd, previousValue]);
return points;
"""
    )


def soc_generator(valid, soc, capacity):
    return (
        plan_guard(valid)
        + f"""const capacityKwh = {capacity};
const raw = hass.states['{soc}']?.state;
const current = raw == null || raw === '' ? NaN : Number(raw);
let previousEnd = null;
for (const r of rows) {{
  const from = Date.parse(r.start), to = Date.parse(r.end);
  if (previousEnd === null && from <= now && Number.isFinite(current)) {{
    points.push([now, current]);
  }} else if (previousEnd !== null && from > previousEnd) {{
    points.push([previousEnd + 1, null]);
  }}
  const value = Number.isFinite(r.end_soc_kwh) ? r.end_soc_kwh / capacityKwh * 100 : null;
  points.push([to, value]);
  previousEnd = to;
}}
return points;
"""
    )


def plan_section(entities=ENTITIES, lang="en", capacity=CAPACITY_KWH):
    """History and projection of load, grid, PV and SoC with plan-state bands."""
    e, t = entities, LABELS[lang]
    bands = "EVAL:" + STATE_BANDS.replace("__PLAN__", e["plan"]).replace(
        "__VALID__", e["valid"]
    ).replace("__LOCALE__", t["locale"])
    series_spec = [
        ("Load", e["load"], "#42a5f5", "load"),
        ("Grid", e["grid"], "#ef5350", "grid"),
        ("PV", e["pv"], "#ffb300", "pv"),
        ("SoC", e["soc"], "#66bb6a", "soc"),
    ]
    chart = {
        "type": "custom:apexcharts-card",
        "section_mode": True,
        "grid_options": {"columns": "full", "rows": 9},
        "header": {
            "show": True,
            "title": t["plan_title"],
            "show_states": True,
            "colorize_states": True,
        },
        "graph_span": "36h",
        "span": {"offset": "+24h"},
        "update_interval": "1min",
        "hours_12": False,
        "now": {"show": True, "label": t["now"], "color": "#9e9e9e"},
        "show": {"last_updated": True},
        "yaxis": [
            {
                "id": "power",
                "decimals": 1,
                "min": "~0",
                "max": "~0",
                "apex_config": {"tickAmount": 6, "title": {"text": t["power_axis"]}},
            },
            {
                "id": "soc",
                "opposite": True,
                "min": 0,
                "max": 100,
                "decimals": 0,
                "apex_config": {"tickAmount": 5, "title": {"text": "SoC [%]"}},
            },
        ],
        "apex_config": {
            "chart": {
                "animations": {"enabled": False},
                "toolbar": {"show": False},
                "events": {"mounted": bands, "updated": bands},
            },
            "annotations": {
                "position": "back",
                "yaxis": [
                    {
                        "y": 0,
                        "yAxisIndex": 0,
                        "borderColor": "#bdbdbd",
                        "borderWidth": 2,
                        "strokeDashArray": 0,
                        "label": {
                            "text": "0 kW",
                            "position": "left",
                            "borderColor": "#757575",
                            "style": {
                                "background": "#424242",
                                "color": "#ffffff",
                                "fontSize": "10px",
                            },
                        },
                    }
                ],
            },
            "legend": {"show": True, "fontSize": "12px"},
            "grid": {"borderColor": "#424242", "strokeDashArray": 2},
            "xaxis": {"labels": {"datetimeUTC": False, "format": "dd.MM HH:mm"}},
            "tooltip": {"shared": False, "x": {"format": "dd.MM HH:mm"}},
        },
        "series": [],
    }
    for name, entity, color, field in series_spec:
        soc = field == "soc"
        chart["series"].append(
            {
                "entity": entity,
                "name": name,
                "color": color,
                "type": "line",
                "yaxis_id": "soc" if soc else "power",
                "unit": "%" if soc else "kW",
                "float_precision": 0 if soc else 2,
                "stroke_width": 2,
                "curve": "monotoneCubic",
                "extend_to": "now",
                "fill_raw": "null",
                "transform": "if (x === null || x === '') return null; const v = Number(x); "
                f"return Number.isFinite(v) ? v / {1 if soc else 1000} : null;",
                "group_by": {"func": "avg", "duration": "30min", "fill": "last"},
                "show": {"legend_value": False},
            }
        )
    for name, _, color, field in series_spec:
        soc = field == "soc"
        chart["series"].append(
            {
                "entity": e["plan"],
                "name": f"{name} · {t['plan_suffix']}",
                "color": color,
                "type": "line",
                "yaxis_id": "soc" if soc else "power",
                "unit": "%" if soc else "kW",
                "float_precision": 0 if soc else 2,
                "stroke_width": 2,
                "stroke_dash": 6,
                "curve": "stepline" if field == "grid" else "monotoneCubic",
                "extend_to": False,
                "show": {"in_header": False, "legend_value": False},
                "data_generator": soc_generator(e["valid"], e["soc"], capacity)
                if soc
                else power_generator(e["valid"], field),
            }
        )
    note = {
        "type": "markdown",
        "grid_options": {"columns": "full", "rows": "auto"},
        "content": t["plan_note"].format(capacity=capacity)
        + f"""
{{% set valid = '{e["valid"]}' %}}
{{% set plan = '{e["plan"]}' %}}
{{% set until = state_attr(plan, 'valid_until') %}}
{{% if has_value(plan) and state_attr(plan, 'refreshing') == true %}}
{t["refreshing"]}
{{% elif is_state(valid, 'on') and until and as_timestamp(until, 0) > as_timestamp(now()) %}}
{{% set coverage = state_attr(valid, 'coverage_end') %}}
{{% if coverage %}}{t["available_until"]} **{{{{ as_local(as_datetime(coverage)).strftime('%d.%m %H:%M') }}}}**.{{% endif %}}
{{% if not state_attr(valid, 'coverage_complete') %}}{t["partial"]}{{% endif %}}
{{% else %}}
{t["stale"]}
{{% endif %}}
""",
    }
    return {
        "type": "grid",
        "column_span": 4,
        "cards": [
            {
                "type": "heading",
                "heading": "Energy Compass",
                "heading_style": "title",
                "icon": "mdi:chart-timeline-variant",
            },
            chart,
            note,
        ],
    }


def level_forecast(valid, level):
    return f"""const now = Date.now();
const a = entity.attributes;
const valid = hass.states['{valid}'];
if (['unknown', 'unavailable'].includes(entity.state) ||
    (!a.refreshing && (valid?.state !== 'on' || !(Date.parse(a.valid_until) > now)))) return [];
const left = Math.max(now, start.getTime());
const coverage = Date.parse(valid?.attributes?.coverage_end);
const right = Math.min(end.getTime(), Number.isFinite(coverage) ? coverage : end.getTime());
if (right <= left) return [];
const points = new Map([[left, 0], [right, 0]]);
for (const row of (a.outlook || [])) {{
  const from = Math.max(left, Date.parse(row.start));
  const to = Math.min(right, Date.parse(row.end));
  if (!(to > from) || !['BOOST', 'CHEAP', 'NORMAL', 'LIMIT'].includes(row.level)) continue;
  const value = row.level === '{level}' ? 1 : 0;
  points.set(from, value);
  points.set(to - 1, value);
  points.set(to, 0);
}}
return [...points].sort((a, b) => a[0] - b[0]);
"""


def consumer_section(entities=ENTITIES, lang="en"):
    """Consumer Compass levels: 4 h of history and a 20 h forecast."""
    e, t = entities, LABELS[lang]
    chart = {
        "type": "custom:apexcharts-card",
        "section_mode": True,
        "grid_options": {"columns": "full", "rows": 4},
        "header": {"show": True, "title": t["consumer_title"], "show_states": False},
        "graph_span": "24h",
        "span": {"offset": "+20h"},
        "update_interval": "1min",
        "hours_12": False,
        "now": {"show": True, "label": t["now"], "color": "#ffb300"},
        "yaxis": [{"min": 0, "max": 1, "show": False}],
        "apex_config": {
            "chart": {
                "animations": {"enabled": False},
                "toolbar": {"show": False},
                "zoom": {"enabled": False},
            },
            "grid": {
                "show": False,
                "padding": {"top": 10, "bottom": 0, "left": 8, "right": 8},
            },
            "markers": {"size": 0},
            "dataLabels": {"enabled": False},
            "xaxis": {
                "labels": {
                    "datetimeUTC": False,
                    "format": "HH:mm",
                    "hideOverlappingLabels": True,
                },
                "tooltip": {"enabled": False},
                "axisBorder": {"show": False},
                "axisTicks": {"show": False},
            },
            "legend": {
                "show": True,
                "position": "bottom",
                "fontSize": "12px",
                "customLegendItems": list(LEVEL_COLORS),
                "markers": {"fillColors": list(LEVEL_COLORS.values())},
                "onItemClick": {"toggleDataSeries": False},
                "onItemHover": {"highlightDataSeries": False},
            },
            "tooltip": {
                "shared": False,
                "intersect": False,
                "custom": f"""EVAL:function({{seriesIndex, dataPointIndex, w}}) {{
  const value = w.globals.series[seriesIndex]?.[dataPointIndex];
  if (value !== 1) return '';
  const timestamp = w.globals.seriesX[seriesIndex]?.[dataPointIndex];
  if (!Number.isFinite(timestamp)) return '';
  const name = w.globals.seriesNames[seriesIndex];
  const date = new Date(timestamp).toLocaleString('{t["locale"]}', {{day:'2-digit', month:'2-digit', hour:'2-digit', minute:'2-digit'}});
  return '<div style="padding:8px 12px"><b>' + name + '</b><br>' + date + '</div>';
}}""",
            },
        },
        "series": [],
    }
    for projected in (False, True):
        for level, color in LEVEL_COLORS.items():
            series = {
                "entity": e["plan"] if projected else e["consumer"],
                "name": f"{level} · {t['forecast'] if projected else t['history']}",
                "color": color,
                "type": "area",
                "curve": "stepline",
                "stroke_width": 0,
                "opacity": 0.55 if projected else 1,
                "extend_to": False if projected else "now",
                "show": {"in_header": False, "legend_value": False},
            }
            if projected:
                series["data_generator"] = level_forecast(e["valid"], level)
            else:
                series["transform"] = f"return x === '{level}' ? 1 : 0;"
                series["fill_raw"] = "zero"
            chart["series"].append(series)
    note = {
        "type": "markdown",
        "grid_options": {"columns": "full", "rows": "auto"},
        "content": f"""**{t["now"]}: {{{{ states('{e["consumer"]}') }}}}** · {t["consumer_note"]}
{{% if state_attr('{e["plan"]}', 'refreshing') == true %}}
{t["consumer_refreshing"]}
{{% elif not is_state('{e["valid"]}', 'on') %}}
{t["consumer_stale"]}
{{% endif %}}""",
    }
    return {"type": "grid", "column_span": 4, "cards": [chart, note]}


def controller_section(entities=ENTITIES, lang="en"):
    """Deye controller mode and runtime; entity IDs are fixed by the package."""
    t = {
        "en": ("Deye controller", "Reason", "Warning", "Uncertain registers"),
        "pl": ("Sterownik Deye", "Powód", "Ostrzeżenie", "Niepewne rejestry"),
    }[lang]
    runtime = "sensor.energy_compass_deye_runtime"
    return {
        "type": "grid",
        "cards": [
            {"type": "heading", "heading": t[0], "icon": "mdi:solar-power-variant"},
            {
                "type": "tile",
                "entity": "input_select.energy_compass_deye_mode",
                "features": [{"type": "select-options"}],
                "grid_options": {"columns": 12},
            },
            {
                "type": "entities",
                "entities": [
                    runtime,
                    "input_boolean.energy_compass_deye_restore_pending",
                    "sensor.energy_compass_deye_plan",
                    "sensor.energy_compass_deye_interval_end",
                    "sensor.energy_compass_deye_next_tou",
                ],
            },
            {
                "type": "markdown",
                "content": f"""{{% set rt = state_attr('{runtime}', 'runtime') or {{}} %}}
**{{{{ rt.get('state', '—') }}}}** · `{{{{ states('{runtime}') }}}}` · {{{{ rt.get('confirmed_mode', '—') }}}}

{t[1]}: {{{{ rt.get('reason', '—') }}}}
{{% if rt.get('warning') %}}{t[2]}: {{{{ rt.warning }}}}{{% endif %}}
{{% if rt.get('uncertain') %}}{t[3]}: {{{{ rt.uncertain | join(', ') }}}}{{% endif %}}""",
            },
        ],
    }


SECTIONS = {
    "plan": plan_section,
    "consumer": consumer_section,
    "controller": controller_section,
}


def dump(value):
    return HEADER + yaml.safe_dump(
        value, sort_keys=False, allow_unicode=True, width=120
    )


def outputs():
    return {
        OUT / "plan_chart.yaml": dump(plan_section()),
        OUT / "consumer_compass_chart.yaml": dump(consumer_section()),
        OUT / "deye_controller.yaml": dump(controller_section()),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed examples are stale"
    )
    parser.add_argument(
        "--print",
        choices=list(SECTIONS),
        help="print one section instead of writing the examples",
    )
    parser.add_argument("--lang", choices=list(LABELS), default="en")
    parser.add_argument(
        "--entity",
        action="append",
        default=[],
        metavar="ROLE=ENTITY_ID",
        help=f"roles: {', '.join(ENTITIES)}",
    )
    parser.add_argument(
        "--capacity",
        type=float,
        default=CAPACITY_KWH,
        help="battery capacity in kWh (plan chart)",
    )
    args = parser.parse_args(argv)
    if args.print:
        entities = ENTITIES | dict(item.split("=", 1) for item in args.entity)
        unknown = set(entities) - set(ENTITIES)
        if unknown:
            parser.error(f"unknown role: {', '.join(sorted(unknown))}")
        kwargs = {"capacity": args.capacity} if args.print == "plan" else {}
        sys.stdout.write(dump(SECTIONS[args.print](entities, args.lang, **kwargs)))
        return 0
    stale = [
        path
        for path, text in outputs().items()
        if not path.exists() or path.read_text() != text
    ]
    if args.check:
        for path in stale:
            print(
                f"stale: {path.relative_to(REPO)} - run python tools/dashboards/build.py",
                file=sys.stderr,
            )
        return 1 if stale else 0
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
