"""Build the static YAML builder page: docs/builder.html + docs/assets/builder/templates.js.

The dashboard and package generators stay the only source. This script renders
their output once per language with placeholder tokens (`__EC_PLAN__`, ...);
docs/assets/builder/builder.js only substitutes validated values for the tokens,
so the page holds no generator logic of its own.

Usage: python tools/build_builder.py [--check]
"""

import argparse
import importlib.util
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
TEMPLATES = DOCS / "assets/builder/templates.js"
PAGE = DOCS / "builder.html"


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, ROOT / path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dashboards = _load("dashboards_build", "tools/dashboards/build.py")
controller = _load("deye_controller_build", "tools/deye_controller/build.py")

# Validation patterns shared with builder.js; values matching them are safe to
# splice into YAML plain scalars, JavaScript strings and Jinja literals.
PATTERNS = {
    "entity": r"^[a-z_]+\.[a-z0-9_]+$",
    "number": r"^[0-9]+(\.[0-9]+)?$",
    "prefix": r"^[a-z0-9_]+$",
}
FIELDS = {
    "plan": ("entity", "sensor.energy_compass_plan", "Plan", "Plan"),
    "valid": (
        "entity",
        "binary_sensor.energy_compass_forecast_valid",
        "Forecast valid",
        "Poprawna prognoza",
    ),
    "consumer": (
        "entity",
        "sensor.energy_compass_consumer_compass",
        "Consumer compass",
        "Kompas zużycia",
    ),
    "soc": (
        "entity",
        "sensor.inverter_deye_battery",
        "Battery SOC (%)",
        "SOC baterii (%)",
    ),
    "load": (
        "entity",
        "sensor.inverter_deye_load_power",
        "Load power (W)",
        "Moc obciążenia (W)",
    ),
    "grid": (
        "entity",
        "sensor.inverter_deye_grid_power",
        "Grid power (W, + import)",
        "Moc sieci (W, + import)",
    ),
    "pv": ("entity", "sensor.inverter_deye_pv_power", "PV power (W)", "Moc PV (W)"),
    "capacity": (
        "number",
        "25",
        "Battery capacity used by Energy Compass (kWh)",
        "Pojemność baterii w Energy Compass (kWh)",
    ),
    "prefix": (
        "prefix",
        controller.DEFAULT_PROGRAM_PREFIX,
        "TOU program entity prefix",
        "Prefiks encji programów TOU",
    ),
}
SECTIONS = {
    "plan": ("Plan chart (ApexCharts)", "Wykres planu (ApexCharts)"),
    "consumer": (
        "Consumer Compass timeline (ApexCharts)",
        "Oś czasu Consumer Compass (ApexCharts)",
    ),
    "controller": ("Deye controller status", "Status sterownika Deye"),
    "package": ("Deye controller package", "Pakiet sterownika Deye"),
}


def token(role):
    return f"__EC_{role.upper()}__"


def dump(value, dumper=yaml.SafeDumper):
    return yaml.dump(
        value, Dumper=dumper, sort_keys=False, allow_unicode=True, width=4096
    )


def section_text(name, lang, values):
    """The YAML for one section; `values` maps roles to IDs, numbers or tokens."""
    if name == "package":
        return dump(controller.package(values["prefix"]), controller.Dumper)
    entities = {role: values[role] for role in dashboards.ENTITIES}
    kwargs = {"capacity": values["capacity"]} if name == "plan" else {}
    return dump(dashboards.SECTIONS[name](entities, lang, **kwargs))


def templates():
    tokens = {role: token(role) for role in FIELDS}
    out = {}
    for lang in dashboards.LABELS:
        for name in SECTIONS:
            text = section_text(name, lang, tokens)
            out.setdefault(name, {})[lang] = {
                "yaml": text,
                "fields": [role for role in FIELDS if token(role) in text],
            }
    return out


def data():
    return {
        "patterns": PATTERNS,
        "fields": {
            role: {
                "token": token(role),
                "kind": kind,
                "example": example,
                "label": {"en": en, "pl": pl},
            }
            for role, (kind, example, en, pl) in FIELDS.items()
        },
        "sections": {
            name: {"label": {"en": en, "pl": pl}} for name, (en, pl) in SECTIONS.items()
        },
        "templates": templates(),
    }


def fill(template, values):
    """Python twin of builder.js fill(); used by the tests."""
    for role, value in values.items():
        if not re.fullmatch(PATTERNS[FIELDS[role][0]], value):
            raise ValueError(f"{role}: {value!r}")
        template = template.replace(token(role), value)
    return template


PAGE_TEMPLATE = """<!doctype html>
<!-- Generated by tools/build_builder.py - do not edit; edit the generator and rebuild. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Energy Compass YAML builder</title>
  <meta name="description" content="Build Energy Compass dashboard sections and the Deye controller package with your own entity IDs.">
  <style>__STYLE__
    .builder { max-width: 60rem; margin: 2rem auto; padding: 0 1.2rem; }
    .builder form { display: grid; gap: .8rem; margin: 1.2rem 0; }
    .builder #fields { display: grid; gap: .8rem; }
    .builder label { display: grid; gap: .25rem; font-weight: 600; }
    .builder input, .builder select { font: inherit; padding: .45rem .6rem; border: 1px solid var(--line);
      border-radius: .3rem; background: var(--surface); color: var(--ink); }
    .builder input[aria-invalid="true"] { border-color: #c62828; }
    .builder textarea { width: 100%; min-height: 24rem; font: .85rem/1.4 ui-monospace, monospace;
      padding: .8rem; border: 1px solid var(--line); border-radius: .35rem; background: var(--surface); color: var(--ink); }
    .builder .error { color: #c62828; min-height: 1.4em; }
    .builder button { font: inherit; padding: .5rem 1rem; border-radius: .3rem; border: 1px solid var(--line);
      background: var(--surface); color: var(--ink); cursor: pointer; }
  </style>
</head>
<body>
<main class="builder">
  <p><a href="index.html">Energy Compass</a> · <a href="guide.en.html">Guide</a> · <a href="guide.pl.html">Przewodnik</a></p>
  <h1>Energy Compass YAML builder</h1>
  <p id="intro"></p>
  <form id="builder" autocomplete="off">
    <label><span id="lang-label">Language</span>
      <select id="lang"><option value="en">English</option><option value="pl">Polski</option></select></label>
    <label><span id="section-label">Section</span><select id="section"></select></label>
    <div id="fields"></div>
  </form>
  <p class="error" id="error" role="alert"></p>
  <textarea id="output" readonly aria-label="YAML"></textarea>
  <p><button type="button" id="copy">Copy</button> <span id="copied"></span></p>
  <p id="note"></p>
</main>
<script src="assets/builder/templates.js"></script>
<script src="assets/builder/builder.js"></script>
</body>
</html>
"""


def page():
    # Same look as docs/index.html; build_guides.py needs `markdown`, CI does not have it.
    index = (DOCS / "index.html").read_text(encoding="utf-8")
    style = re.search(r"<style>(.*?)</style>", index, re.DOTALL).group(1).rstrip()
    return PAGE_TEMPLATE.replace("__STYLE__", style)


def outputs():
    js = (
        "// Generated by tools/build_builder.py - do not edit; edit the generators and rebuild.\n"
        "window.EC_BUILDER = "
        + json.dumps(data(), ensure_ascii=False, indent=1)
        + ";\n"
    )
    return {TEMPLATES: js, PAGE: page()}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed files are stale"
    )
    args = parser.parse_args(argv)
    stale = [
        path
        for path, text in outputs().items()
        if not path.exists() or path.read_text() != text
    ]
    if args.check:
        for path in stale:
            print(
                f"stale: {path.relative_to(ROOT)} - run python tools/build_builder.py",
                file=sys.stderr,
            )
        return 1 if stale else 0
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
